services:
  bob-pr:
    build:
      context: ../../
      dockerfile: dev.Dockerfile
    image: lnd-dev:backward-compat-test-build
    container_name: bob-pr
    restart: unless-stopped
    ports:
      - 10012:10005
      - 9742:5521
      - 8092:5050
    networks:
      regtest:
        aliases:
          - bob
    volumes:
      - "bob:/root/.lnd"
    depends_on:
      - bitcoind
    command: >
      lnd
      --logdir=/root/.lnd
      --alias=bob
      --rpclisten=0.0.0.0:10005
      --restlisten=0.0.0.0:5050
      --color=#cccccc
      --noseedbackup
      --flokicoin.active
      --flokicoin.regtest
      --flokicoin.node=bitcoind
      --bitcoind.rpchost=bitcoind
      --bitcoind.rpcuser=lightning
      --bitcoind.rpcpass=lightning
      --bitcoind.zmqpubrawblock=tcp://bitcoind:28332
      --bitcoind.zmqpubrawtx=tcp://bitcoind:28333
      --debuglevel=debug
      --externalip=bob
      --tlsextradomain=bob
      --accept-keysend
      --protocol.option-scid-alias
      --protocol.zero-conf
      --protocol.simple-taproot-chans
      --trickledelay=50

  dave-pr:
    image: lnd-dev:backward-compat-test-build
    container_name: dave-pr
    restart: unless-stopped
    ports:
      - 10014:10005
      - 9744:5521
      - 8094:5050
    networks:
      regtest:
        aliases:
          - dave
    volumes:
      - "dave:/root/.lnd"
    depends_on:
      - bitcoind
    command: >
      lnd
      --logdir=/root/.lnd
      --alias=dave
      --rpclisten=0.0.0.0:10005
      --restlisten=0.0.0.0:5050
      --color=#cccccc
      --noseedbackup
      --flokicoin.active
      --flokicoin.regtest
      --flokicoin.node=bitcoind
      --bitcoind.rpchost=bitcoind
      --bitcoind.rpcuser=lightning
      --bitcoind.rpcpass=lightning
      --bitcoind.zmqpubrawblock=tcp://bitcoind:28332
      --bitcoind.zmqpubrawtx=tcp://bitcoind:28333
      --debuglevel=debug
      --externalip=dave
      --tlsextradomain=dave
      --accept-keysend
      --protocol.option-scid-alias
      --protocol.zero-conf
      --protocol.simple-taproot-chans
      --trickledelay=50
      --db.backend=sqlite
      --db.use-native-sql
